package com.amberance;

import java.util.HashSet;

public class Phrases {
	
	public static String[] leads = {
			"We're always impressed by the #athleticism, #flexibility and youthful #beauty of %s.",
			"%s's #fitness, #flexibility, and #friendliness never cease to amaze us.",
			"%s's #athleticism, #flexibility, and #energy is #contagious.",
			"Just one more reason to follow %s. And we assure you, there are many.",
			"How many reasons do you need to follow  %s? Believe us when we say there are plenty of them.",
			"Need a reason to follow %s? Here's one of many.",
			"Incredible #athlete. Incredible #flexibility. An amazing #fashionsense. %s",
			"A fantastic #athlete. Extremely adaptable. An incredible #fashionsense. %s",
			"Tremendous #athletic ability. Extremely adaptable. And a perfect sense of #style and #fashion. %s",
			"%s has amazing #athletic ability and impressive #flexibility. Not to mention #fashionstyle... ",
			"%s speaks to athleticism, #flexibility and style.",
			"What do sponsors look for in an #ambassador? Energy, style and #charisma are a few of the #xfactors %s has.",
			"What qualities do sponsors seek in a #ambassador? Among the #xfactors %s possesses are energy, style, and #charisma.",
			"Want to be come an influencer? What qualities do #infleuncers need to have? The #xfactors %s possesses include #beauty, #charisma, and energy.",
			"What qualities do #infleuncers and #ambassadors need to have? The attributes %s possesses include #fashionsense, youth, charisma, and energy.",
			"What qualities do #infleunceambassadors need to have to be successful? The attributes %s possesses include fashion style, youth, friendliness, and energy.",
			"The #xfactors %s possesses include personality, athleticism, and charisma, just to name a few.",
			"Youth. Beauty. Energy. Style. %s",
			"%s's #beauty and #athleticism is astounding at an international level",
			"We're always amazed by %s's universally impressive combination of #strength, #beauty and #fitness.",
			"%s: Beauty. Fashion. Personality. Style.",
			"%s brings you your #fitnessmotivation for the day.",
			"%s: All we can say is #incredible.",
			"%s: Always setting the standard.",
			"%s: Beauty, fashion and style.",
			"How can you not be impressed by %s?",
			"%s is an absolute must-follow.",
			"%s's success is no accident. Strength, fitness, perseverence and hard work never is.",
			"We're always amazed by %s's #fashionsense and incredible demonstration of #fitness and #athleticism.",
			"%s proves that #strength, #beauty and #athleticism are not mutually exclusive traits.",
			"Everything %s wears becomes a must-have item for anyone who views her photos. A true #gymnasticsambassador.",
			"Who wouldn't want %s as an #ambassador for their clothing line? Everything she wears always seems to fit perfectly.",
			"Every time %s poses in front of the camera she makes a statement.",
			"Whenever %s gets captured by the camera she makes a statement.",
			"There are no rest days if you want #strengthandbeauty like %s.",
			"Rest day? You don't get rest days if you want to be both #strongandbeautiful like %s. So get to work. #gymmotivation #fitnessmotivation ",
			"There are never enough casual day or training pics of %s. Always an amazing demonstration of #beautyandfitness",
			"%s is always ready to take on the day with #strength, #beauty and #positivity.",
			"%s always shoots for the moon, but in the world of #gymnasticsinfluencers, she's a star.",
			"A #influencer like %s always stands out from the crowd. A true star.",
			"%s always looks like she's having so much fun, both in and out of the studio. A definite #superstar in the world of #fitness and #gymnastics.",
			"%s is always such an inspiration. Follow this talented #influencer and #ambassador.",
			"If you haven't followed %s yet, you should.",
			"%s is a #gymnasticsinfluencer we hope to see much more of in the future.",
			"%s has got the right stuff. Everything it takes to be a successful #ambassador and #influencer in the #gymnastics world.",
			"Just a few photos of %s, but she is a #gymnasticsambassador we hope to see much more of in the future.",
			"Is it possible for someone to win the Internet? If it is, we think %s just has.",
			"Who won the Internet today? %s is definitely a contende with her incredible #athleticism, #gymnastics skills and beauty.",
			"We've just declared it: %s has just won the Internet. Given her athleticism, talent and beauty, there isn't even a runner-up to this young #influencer.",
			"#Fitness, #fashion, #elegance and grace? That's why we decalare the Internet won by %s.",
			"%s just won Instagram with posts like these. A definite #influencer to follow.",
			
			
	};
	
	public static String[] closings = {
			"\n Links in bio.",
			"\n Follow us for more.",
			"\n More details in bio.",
			"\n Check bio for more details.",
			"\n Follow. Comment. Contribute.",
			"\n Change the world by being yourself.",
			"\n Every moment is a fresh beginning.",
			"\n Never regret anything that made you smile. ",
			"\n Aspire to inspire.  ",
			"\n Everything you can imagine is real. ",
			"\n Simplicity is the ultimate #sophistication.",
			"\n Whatever you do, do it well. ",
			"\n What we think, we become",
			"\n Check our links in the bio.",
			"\n Check out more links in our bio.",
			"\n Links on our profile page.",
			"\n Comment. Like. Follow.",
			"\n Follow. Comment. Contribute.",
			"\n Have enough courage to start and enough heart to finish..",
			"\n Oh, the things you can find, if you don’t stay behind.",
			"\n Determine your priorities and focus on them. ",
			"\n Be so good they can’t ignore you.  ",
			"\n Yesterday you said tomorrow. Just do it. ",
			"\n I don’t need it to be easy, I need it to be worth it.",
			"\n To live will be an awfully big adventure. ",
			"\n Try to be a rainbow in someone’s cloud. ",
			"\n Find our links in the bio.",
			"\n Want more? The links are in our bio.",
			"\n Strive for greatness.",
			"\n And still, I rise.",
			"\n Follow. Comment. Contribute. Give back. Be kind.",
			"\n The time is always right to do what is right.",
			"\n Let the beauty of what you love be what you do. ",
			"\n May your choices reflect your hopes, not your fears.",
			"\n Happiness depends upon ourselves.   ",
			"\n Change the game, don’t let the game change you.  ",
			"\n The meaning of life is to give life meaning. ",
			"\n I have nothing to lose but something to gain. ",
			"\n Try hard to be a #rainbow when the sky is full of clouds. ",
			"\n The past cannot be changed, but we can always build for a new tomorrow. ",
			"\n Shoot for the moon, and if you miss, you will land upon the stars. ",
			"\n Be a flamingo and stay balanced. ",
	};

	
	public static String[] hashtags = {
			" #likedance ",
			" #leotards",
			" #leotardsforgymnastics",
			" #leotardslovers",
			" #gymnasticsleotards",
			" #dance",
			" #dancer",
			" #dancechallenge",
			" #dancemoms",
			" #dancers",
			" #dancephotos",
			" #dancephotography",
			" #dancelover",
			" #dancelife",
			" #danceclass",
			" #dancelove",
			" #dancechoreography",
			" #dancegoals",
			" #dancestudio",
			" #dancewear",
			" #dancefitness",
			" #dancepractice",
			" #dancersofinstagram",
			" #dancelifestyle",
			" #dancecompetition",
			" #danceislife",
			" #dancesport",
			" #dances",
			" #dancephotographer",
			" #contortionist",
			" #contortion",
			" #contortiontraining",
			" #contortionistsofinstagram",
			" #contortionistgoals",
			" #contortionkids",
			" #contortiongirl",
			" #contortionpractice",
			" #contortionistintraining",
			" #contortiondreams",
			" #gymnastics",
			" #gymnasticsdrills",
			" #danceshoutouts",
			" #gymshoutouts",
			" #shoutout",
			" #gymnasticsshoutouts",
			" #gymnasticsshoutout",
			" #gymnasticslife",
			" #gymnasticstraining",
			" #gymnasticsfun",
			" #gymnasticsforlife",
			" #gymnasticsbodies",
			" #gymnasticsmeet",
			" #rythmicgymnastics",
			" #gymnasticsmom",
			" #gymnasticsgirl",
			" #gymnasticsislife",
			" #gymnasticslove",
			" #gymnasticsquotes",
			" #gymnasticsprogressions",
			" #gymnasticsconditioning",
			" #stretching",
			" #stretches",
			" #splits",
			" #splitsprogress",
			" #splitstraining",
			" #splitschallenge",
			" #middlesplits",
			" #splitseverywhere",
			" #oversplits",
			" #frontsplits",
			" #splitspractice",
			" #splitsstretch",
			" #splitsvariation",
			" #splitsfordays",
			" #standingsplits",
			" #splitslove",
			" #yogasplits",
			" #polesplits",
			" #yoga",
			" #yogainspiration",
			" #yogapractice",
			" #yogapants",
			" #yogalove",
			" #yogagirl",
			" #yogaeveryday",
			" #yogachallenge",
			" #yogapose",
			" #yogafun",
			" #yogagram",
			" #yogajournet",
			" #yogalife",
			" #yogaphotography",
			" #lulu",
			" #absworkout",
			" #swimsuitmodel",
			" #beachgymnastics",
			" #fashionphotography ",
			" #dancekids ",
			" #beautifulmodel ",
			" #circusarts ",
			" #aerialacrobat ",
			" #flexible_repost ",
			" #worldwideballet ",
			" #karisma ",
			" #funinthesun ",
			" #contortion ",
			" #tweenstyle ",
			" #polesportkids ",
			" #inspired ",
			" #acrobatics ",
			" #kidmodelsearch ",
			" #flexiblity ",
			" #stronggymnast ",
			" #balletbeautifulgirls ",
			" #photographgym ",
			" #innerbeauty ",
			" #fitbody ",
			" #HandstandDay ",
			" #showingoff ",
			" #flip ",
			" #artistic ",
			" #photo ",
			" #abs ",
			" #workout ",
			" #kidsswimwear ",
			" #fitnesslife ",
			" #fitkids ",
			" #dancersoninsta ",
			" #dancers ",
			" #photoshooting ",
			" #fitness ",
			" #adventureawaits ",
			" #sportsclothes ",
			" #fitnessmotivation ",
			" #splitstraining ",
			" #minimodelfeature ",
			" #gymphotoshoot ",
			" #splitsprogress ",
			" #backbend ",
			" #stretch ",
			" #happiness ",
			" #beautywithin ",
			" #insta_dancee ",
			" #girlsswimwear ",
			" #gymnasticsshoutouts ",
			" #tween ",
			" #stretchingitout ",
			" #teenstyle ",
			" #summerfun ",
			" #aerialist ",
			" #dancephotographer ",
			" #risingtalents ",
			" #muscles ",
			" #PhotoShooting ",
			" #fashionmodel ",
			" #yogafriends ",
			" #newtalent ",
			" #gymnasticslife ",
			" #contortionist ",
			" #bossgirl ",
			" #dowhatyoulove ",
			" #naturalbeauty ",
			" #flexible_people ",
			" #tinygymnast ",
			" #flexiblekid ",
			" #gymnastique ",
			" #swimwearmodelling ",
			" #beautifulgirls ",
			" #flexybility ",
			" #tweenfashions ",
			" #kidsdancer ",
			" #mindset ",
			" #bebold ",
			" #dancersworld ",
			" #followers ",
			" #gym ",
			" #fitnesswear ",
			" #workoutmotivation",
			" #gymmotivation ",
			" #instafun ",
			" #sportkids ",
			" #talented ",
			" #contortionprogress ",
			" #topmodel ",
			" #instasports ",
			" #acro ",
			" #beinspired ",
			" #fashionphotos ",
			" #sport ",
			" #splits ",
			" #gymnasticspractice ",
			" #contortionpractice ",
			" #beautiful ",
			" #yogaposes ",
			" #tumbling ",
			" #flexibilitytraining ",
			" #leo ",
			" #stronggirl ",
			" #dance ",
			" #models ",
			" #middlesplits ",
			" #strongkids ",
			" #tumblrgirl ",
			" #modelo ",
			" #sportlife ",
			" #mobility ",
			" #contortiontraining ",
			" #cardio ",
			" #strongandbendy ",
			" #contortionistsofinstagram ",
			" #kids ",
			" #flexi ",
			" #beachgirl ",
			" #activewear ",
			" #successdriven ",
			" #sportster ",
			" #cirqfit ",
			" #gymnastsrelate ",
			" #yogapractice ",
			" #kidmodels ",
			" #strength ",
			" #activelifestyle ",
			" #kidmodelsofinstagram ",
			" #healthyteen ",
			" #gymnasstics ",
			" #contortion ",
			" #sportsmodel ",
			" #thisgirlcan ",
			" #kidsmodelsstyle ",
			" #athletes ",
			" #cheerful_dancers ",
			" #cheerleading ",
			" #cheersport ",
			" #teenactivewear ",
			" #flexiandfit ",
			" #fashionblogger ",
			" #covermodel ",
			" #gymnast ",
			" #positiveenergy ",
			" #motivation ",
			" #supermodel ",
			" #contortionclass ",
			" #teenagerfashion ",
			" #dancesport ",
			" #flexgym ",
			" #gymnasts_relate ",
			" #onpoint ",
			" #acroyoga ",
			" #athletics ",
			" #absworkout ",
			" #bikiniseason ",
			" #modeling ",
			" #teengirl ",
			" #trainhard ",
			" #flexiblegirls ",
			" #youngbeauty ",
			" #gymnasticsshoutout ",
			" #workout ",
			" #teenfitess  "};
	
	
	public static String generatePostData(String username) {
		
		
			int randomLead = (int) (Math.random() * leads.length);
			int randomClosing = (int) (Math.random() * closings.length);
			String lead = leads[randomLead];
			
			if(username==null || username.trim().length()==0) {
				username = "this #gymnasticsinfluencer";
			} else {
				username = "@" + username;
			}
			
			lead = String.format(lead, username);
			String closing = closings[randomClosing];
			return lead + "\n" + generateHashtags() + "\n" +  closing;

	}
	
	
	public static String generateHashtags() {
		HashSet<String> set = new HashSet<String>();
		int numberOfTags = 5 + (int) (Math.random() * 20);
		while (numberOfTags < 15) {
			numberOfTags = numberOfTags + (int) (Math.random() * 20);
		}
		
		set.add("#influenceambassador");
		set.add("#gymnasticsinfluencer");
		set.add("#influencer");
		set.add("#younginfluencer");
		
		
		while (set.size() < numberOfTags) {
			int tagToAdd = (int)(Math.random() * hashtags.length);
			set.add(hashtags[tagToAdd]);
		}
		String tags = set.toString();
		tags = tags.replace("[", "");
		tags = tags.replace("]", "");
		tags = tags.replace(",", "");
		System.out.println("\nNumber of tags: " + set.size());
		return tags;
		
	}
	
	
	
	
	
}
